=== AlanFSlaterCompanyNet/ShrForms/designs/allfields/formDesignSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for PerForm Open Form Designs",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "description": "The title of the form design.",
      "minLength": 1
    },
    "formTitle": {
      "type": "string",
      "description": "Used to define the titles of instances of forms created from this design",
      "minLength": 1
    },
    "editRole": {
      "type": "string",
      "description": "Role for editing the form",
      "minLength": 1
    },
    "readRole": {
      "type": "string",
      "description": "Role for editing the form",
      "minLength": 1
    },
    "outputTable": {
      "$ref": "#/definitions/outputTablePropertyDefinition"
    },
    "hierarchical": {
      "$ref": "#/definitions/hierarchicalPropertyDefinition"
    },
    "pages": {
      "$ref": "#/definitions/pages"
    }
  },
  "required": [
    "title",
    "formTitle",
    "pages"
  ],
  "definitions": {
    "pages": {
      "description": "List of Pages in the Form",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/pageDesign"
      }
    },
    "pageDesign": {
      "description": "An individual Page in the Form",
      "type": "object",
      "properties": {
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "title": {
          "description": "The user friendly name of the Form",
          "type": "string"
        },
        "editRole": {
          "type": "string",
          "description": "Role for editing this page in the form",
          "minLength": 1
        },
        "fields": {
          "$ref": "#/definitions/fields"
        },
        "sectionLevel": {
          "description": "section level - start at 1 and increase",
          "type": "integer"
        }
      },
      "required": [ "name", "title", "fields" ]
    },
    "fields": {
      "description": "The list of Fields in the Page",
      "type": "array",
      "items": {
        "$ref": "#/definitions/fieldDesign"
      }
    },
    "fieldDesign": {
      "oneOf": [
        { "$ref": "#/definitions/textFieldDesign" },
        { "$ref": "#/definitions/textAreaFieldDesign" },
        { "$ref": "#/definitions/numericFieldDesign" },
        { "$ref": "#/definitions/currencyFieldDesign" },
        { "$ref": "#/definitions/choiceFieldDesign" },
        { "$ref": "#/definitions/staticFieldDesign" },
        { "$ref": "#/definitions/submitFieldDesign" },
        { "$ref": "#/definitions/linkedPageGridFieldDesign" },
        { "$ref": "#/definitions/closeFieldDesign" },
        { "$ref": "#/definitions/linkedPageSelectFieldDesign" },
        { "$ref": "#/definitions/dateFieldDesign" },
        { "$ref": "#/definitions/booleanFieldDesign" },
        { "$ref": "#/definitions/tableFieldDesign" },
        { "$ref": "#/definitions/blankFieldDesign" }
      ]
    },

    "textFieldDesign": {
      "description": "Text field",
      "type": "object",
      "properties": {
        "type": { "enum": [ "text" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "readonly": { "$ref": "#/definitions/readonlyPropertyDefinition" },
        "hidden": { "$ref": "#/definitions/hiddenPropertyDefinition" },
        "outputColumn": { "$ref": "#/definitions/outputColumnPropertyDefinition" },
        "label": { "$ref": "#/definitions/labelPropertyDefinition" },
        "validation": { "$ref": "#/definitions/validationPropertyDefinition" },
        "width": { "$ref": "#/definitions/widthPropertyDefinition" },
        "calculation": { "$ref": "#/definitions/calculationPropertyDefinition" },
        "required": { "$ref": "#/definitions/requiredPropertyDefinition" },
        "activation": { "$ref": "#/definitions/activationPropertyDefinition" },
        "activationMode": { "$ref": "#/definitions/activationModePropertyDefinition" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "tooltip": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      },
      "required": [ "type", "name", "label" ]
    },
    "textAreaFieldDesign": {
      "description": "Text Area field",
      "type": "object",
      "properties": {
        "type": { "enum": [ "textarea" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "readonly": { "$ref": "#/definitions/readonlyPropertyDefinition" },
        "hidden": { "$ref": "#/definitions/hiddenPropertyDefinition" },
        "outputColumn": { "$ref": "#/definitions/outputColumnPropertyDefinition" },
        "label": { "$ref": "#/definitions/labelPropertyDefinition" },
        "validation": { "$ref": "#/definitions/validationPropertyDefinition" },
        "width": { "$ref": "#/definitions/widthPropertyDefinition" },
        "calculation": { "$ref": "#/definitions/calculationPropertyDefinition" },
        "required": { "$ref": "#/definitions/requiredPropertyDefinition" },
        "activation": { "$ref": "#/definitions/activationPropertyDefinition" },
        "activationMode": { "$ref": "#/definitions/activationModePropertyDefinition" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "tooltip": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      },
      "required": [ "type", "name", "label" ]
    },
    "numericFieldDesign": {
      "description": "Numeric field",
      "type": "object",
      "properties": {
        "type": { "enum": [ "numeric" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "readonly": { "$ref": "#/definitions/readonlyPropertyDefinition" },
        "hidden": { "$ref": "#/definitions/hiddenPropertyDefinition" },
        "outputColumn": { "$ref": "#/definitions/outputColumnPropertyDefinition" },
        "label": { "$ref": "#/definitions/labelPropertyDefinition" },
        "maximumValue": { "type": "number" },
        "minimumValue": { "type": "number" },
        "decimalPlaces": { "$ref": "#/definitions/decimalPlacesPropertyDefinition" },
        "percentage": { "type": "boolean" },
        "width": { "$ref": "#/definitions/widthPropertyDefinition" },
        "validation": { "$ref": "#/definitions/validationPropertyDefinition" },
        "calculation": { "$ref": "#/definitions/calculationPropertyDefinition" },
        "required": { "$ref": "#/definitions/requiredPropertyDefinition" },
        "activation": { "$ref": "#/definitions/activationPropertyDefinition" },
        "activationMode": { "$ref": "#/definitions/activationModePropertyDefinition" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "tooltip": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      },
      "required": [ "type", "name", "label" ]
    },
    "currencyFieldDesign": {
      "description": "Currency field",
      "type": "object",
      "properties": {
        "type": { "enum": [ "currency" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "readonly": { "$ref": "#/definitions/readonlyPropertyDefinition" },
        "hidden": { "$ref": "#/definitions/hiddenPropertyDefinition" },
        "outputColumn": { "$ref": "#/definitions/outputColumnPropertyDefinition" },
        "label": { "$ref": "#/definitions/labelPropertyDefinition" },
        "maximumValue": { "type": "number" },
        "minimumValue": { "type": "number" },
        "decimalPlaces": { "$ref": "#/definitions/decimalPlacesPropertyDefinition" },
        "width": { "$ref": "#/definitions/widthPropertyDefinition" },
        "validation": { "$ref": "#/definitions/validationPropertyDefinition" },
        "calculation": { "$ref": "#/definitions/calculationPropertyDefinition" },
        "required": { "$ref": "#/definitions/requiredPropertyDefinition" },
        "activation": { "$ref": "#/definitions/activationPropertyDefinition" },
        "activationMode": { "$ref": "#/definitions/activationModePropertyDefinition" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "tooltip": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      },
      "required": [ "type", "name", "label" ]
    },
    "choiceFieldDesign": {
      "description": "Choice field",
      "type": "object",
      "properties": {
        "type": { "enum": [ "choice" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "readonly": { "$ref": "#/definitions/readonlyPropertyDefinition" },
        "hidden": { "$ref": "#/definitions/hiddenPropertyDefinition" },
        "outputColumn": { "$ref": "#/definitions/outputColumnPropertyDefinition" },
        "label": { "$ref": "#/definitions/labelPropertyDefinition" },
        "values": { "$ref": "#/definitions/choiceValuesPropertyDefinition" },
        "width": { "$ref": "#/definitions/widthPropertyDefinition" },
        "validation": { "$ref": "#/definitions/validationPropertyDefinition" },
        "calculation": { "$ref": "#/definitions/calculationPropertyDefinition" },
        "multiple": {
          "description": "Set to allow multiple values",
          "type": "boolean"
        },
        "activation": { "$ref": "#/definitions/activationPropertyDefinition" },
        "activationMode": { "$ref": "#/definitions/activationModePropertyDefinition" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "tooltip": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "csv": { "$ref": "#/definitions/csvPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      },
      "required": [ "type", "name", "label" ]
    },
    "staticFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "static" ] },
        "style": { "enum": [ "heading", "card", "htmlcard" ] },
        "level": {
          "type": "integer",
          "minimum": 1,
          "maximum": 6
        },
        "title": { "type": "string" },
        "text": { "type": "string" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "borderTop": { "type": "boolean" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      },
      "required": [ "type", "style" ]
    },
    "submitFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "submit" ] },
        "message": { "type": "string" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "tooltip": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      }
    },
    "linkedPageGridFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "linkedPageGrid" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "label": { "$ref": "#/definitions/labelPropertyDefinition" },
        "page": { "type": "string" },
        "createLabel": { "type": "string" },
        "descriptionFields": { "$ref": "#/definitions/descriptionFieldPropertyDefinition" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      }
    },
    "closeFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "close" ] },
        "closeLabel ": { "type": "string" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "tooltip": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      }
    },
    "linkedPageSelectFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "linkedPageSelect" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "label": { "$ref": "#/definitions/labelPropertyDefinition" },
        "page": { "type": "string" },
        "descriptionFields": { "$ref": "#/definitions/descriptionFieldPropertyDefinition" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "tooltip": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      }
    },
    "dateFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "date" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "readonly": { "$ref": "#/definitions/readonlyPropertyDefinition" },
        "hidden": { "$ref": "#/definitions/hiddenPropertyDefinition" },
        "outputColumn": { "$ref": "#/definitions/outputColumnPropertyDefinition" },
        "label": { "$ref": "#/definitions/labelPropertyDefinition" },
        "width": { "$ref": "#/definitions/widthPropertyDefinition" },
        "validation": { "$ref": "#/definitions/validationPropertyDefinition" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "tooltip": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" },
        "monthYearOnly": {
          "description": "Only allow month and year to be selected",
          "type": "boolean"
        }
      },
      "required": [ "type", "name", "label" ]
    },
    "booleanFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "boolean" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "readonly": { "$ref": "#/definitions/readonlyPropertyDefinition" },
        "hidden": { "$ref": "#/definitions/hiddenPropertyDefinition" },
        "outputColumn": { "$ref": "#/definitions/outputColumnPropertyDefinition" },
        "label": { "$ref": "#/definitions/labelPropertyDefinition" },
        "width": { "$ref": "#/definitions/widthPropertyDefinition" },
        "validation": { "$ref": "#/definitions/validationPropertyDefinition" },
        "help": { "$ref": "#/definitions/helpPropertyDefinition" },
        "labelTrue": { "type": "string" },
        "labelFalse": { "type": "string" },
        "tooltipTrue": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "tooltipFalse": { "$ref": "#/definitions/tooltipPropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" },
        "checkbox": { "type": "boolean" }
      },
      "required": [ "type", "name", "label" ]
    },
    "tableFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "table" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "headers": {
          "description": "Column headers",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "headerAlignment": {
          "enum": [ "left", "right", "center" ]
        },
        "messageWidth": { "$ref": "#/definitions/widthPropertyDefinition" },
        "children": {
          "description": "The list of rows in this table",
          "type": "array",
          "items": {
            "$ref": "#/definitions/tableRowFieldDesign"
          }
        },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      },
      "required": [ "type", "name", "children", "headers" ]
    },
    "tableRowFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "tablerow" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "header": {
          "description": "Row header",
          "type": "string"
        },
        "children": {
          "description": "The list of Fields in this row",
          "type": "array",
          "items": {
            "$ref": "#/definitions/fieldDesign"
          }
        },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      },
      "required": [ "type", "name", "children" ]
    },
    "blankFieldDesign": {
      "type": "object",
      "properties": {
        "type": { "enum": [ "blank" ] },
        "name": { "$ref": "#/definitions/namePropertyDefinition" },
        "aux": { "$ref": "#/definitions/auxPropertyDefinition" }
      },
      "required": [ "type", "name" ]
    },

    "namePropertyDefinition": {
      "description": "Names can only be made up of lowercase letters, digits and underscore",
      "type": "string",
      "pattern": "^[a-z0-9_]+$"
    },
    "outputColumnPropertyDefinition": {
      "description": "Output columns can only be made up of lowercase letters, digits and underscore",
      "type": "string",
      "pattern": "^[a-z0-9_]+$"
    },
    "readonlyPropertyDefinition": {
      "description": "Is the field readonly?",
      "type": "boolean"
    },
    "hiddenPropertyDefinition": {
      "description": "Is the field hidden?",
      "type": "boolean"
    },
    "outputTablePropertyDefinition": {
      "description": "Output table name",
      "type": "string",
      "pattern": "^[A-Za-z0-9_]+$"
    },
    "hierarchicalPropertyDefinition": {
      "description": "Is this a hierarchical form?",
      "type": "boolean"
    },
    "labelPropertyDefinition": {
      "type": "string",
      "description": "Field label display to the user",
      "minLength": 1
    },
    "validationPropertyDefinition": {
      "type": "string"
    },
    "calculationPropertyDefinition": {
      "type": "string"
    },
    "decimalPlacesPropertyDefinition": {
      "type": "integer",
      "minimum": 0,
      "maximum": 4
    },
    "widthPropertyDefinition": {
      "type": "integer",
      "minimum": 1,
      "maximum": 8
    },
    "choiceValuesPropertyDefinition": {
      "description": "List of values for a choice field",
      "type": "array",
      "items": {
        "description": "A value and a label",
        "type": "array",
        "minItems": 2,
        "maxLength": 2,
        "items": { "type": "string" }
      }
    },
    "requiredPropertyDefinition": {
      "description": "Must this field contain a value?",
      "type": "boolean"
    },
    "activationPropertyDefinition": {
      "description": "script to decide whether to activate this field or not",
      "type": "string"
    },
    "activationModePropertyDefinition": {
      "enum": [ "hide", "disable" ]
    },
    "descriptionFieldPropertyDefinition": {
      "description": "Array of fields extracted from linked pages to create definiton",
      "type": "array",
      "items": [ { "type": "string" } ]
    },
    "helpPropertyDefinition": {
      "description": "HTML help text shown in modal dialog opened by icon next to field",
      "type": "string"
    },
    "tooltipPropertyDefinition": {
      "description": "HTML tooltip text shown automatically for a field",
      "type": "string"
    },
    "auxPropertyDefinition": {
      "description": "Auxiliary values associated with a field",
      "type": "object"
    },
    "csvPropertyDefinition": {
      "description": "Properties for loading data from CSV files",
      "type": "object",
      "properties": {
        "file": {
          "description": "the CSV file name containing the data to be loaded",
          "type": "string"
        },
        "labelColumn": {
          "description": "the column name in the CSV data for labels displayed to users",
          "type": "string"
        },
        "valueColumn": {
          "description": "the column name in the CSV data for values to be stored and reported",
          "type": "string"
        }
      },
      "required": [ "file", "labelColumn", "valueColumn" ]
    }
  }
}

=== AlanFSlaterCompanyNet/ShrForms/designs/design0/design0_1_13.json
{
  "$schema": "https://raw.githubusercontent.com/AlanFSlaterCompanyNet/PerFormOpen/master/PerFormOpen/schemas/formDesignSchema.json",
  "title": "A Form",
  "formTitle": "A Demo Form",
  "outputTable": "MyFirstOutputs",
  "readRole": "reader",
  "editRole": "editor",
  "pages": [
    {
      "name": "section1",
      "title": "Section One",
      "sectionLevel": 1,
      "fields": []
    },
    {
      "name": "subsection1",
      "title": "Subsection One",
      "sectionLevel": 2,
      "fields": []
    },
    {
      "name": "page1",
      "title": "Page One",
      "fields": [
        {
          "name": "date1",
          "label": "Date",
          "type": "date"
        },
        {
          "name": "date2",
          "label": "Date - month & year only",
          "type": "date",
          "monthYearOnly":  true
        },
        {
          "name": "t1000",
          "type": "text",
          "label": "A text field",
          "tooltip": "This is a tooltip that can contain explanatory text for the field - don't say 'banana'",
          "validation": "$value != 'banana'",
          "validationMessage": "Please don't say that",
          "help": "We can add some help text here"
        },
        {
          "name": "bool0",
          "label": "First",
          "type": "boolean",
          "help": "This is a boolean"
        },
        {
          "name": "bool1",
          "label": "Second",
          "type": "boolean",
          "help": "This is also a boolean, but the labels for the true and false values have been changed",
          "labelTrue": "Positive",
          "labelFalse": "Negative"
        },
        {
          "name": "bool2",
          "label": "Checkbox",
          "type": "boolean",
          "checkbox": true
        },
        {
          "name": "activated",
          "label": "Activated",
          "type": "text",
          "activation": "!bool2",
          "tooltip": "Required if checkbox false"
        },
        {
          "name": "percentage1",
          "label": "Percentage",
          "type": "numeric",
          "percentage": true,
          "required": true
        },
        {
          "name": "c1",
          "label": "Currency",
          "type": "currency"
        },
        {
          "name": "n",
          "label": "Numeric > 10",
          "type": "numeric",
          "minimumValue": 10
        },
        {
          "name": "a",
          "label": "Field A",
          "type": "numeric",
          "decimalPlaces": 1,
          "validation": "$value > 5",
          "validationMessage": "Must be greater than 5"
        },
        {
          "name": "b",
          "label": "Field B",
          "type": "numeric",
          "decimalPlaces": 1
        },
        {
          "name": "calc1",
          "label": "Calculated",
          "type": "numeric",
          "calculation": "a/b",
          "validation": "$value > 1",
          "validationMessage": "Should be > 1",
          "tooltip": "=a/b",
          "help": "A longer explanation of what the calculation is"
        },
        {
          "name": "lenders",
          "type": "choice",
          "label": "Lenders (from CSV)",
          "csv": {
            "file": "lenders.csv",
            "labelColumn": "Lender",
            "valueColumn": "Short code"
          },
          "help": "A choice field where the values are read from a CSV file"
        }
      ]
    },
    {
      "name": "section2",
      "title": "Section Two",
      "sectionLevel": 1,
      "fields": []
    },
    {
      "name": "page3",
      "title": "Second page",
      "fields": [
        {
          "name": "page32",
          "type": "text",
          "label": "Field on page 2",
          "help": "Help text"
        }
      ]
    },
    {
      "name": "submit",
      "title": "Submit Page",
      "fields": [
        {
          "name": "submit",
          "type": "submit",
          "message": "Are you sure you want to submit this test form?",
          "width": 5
        }
      ]
    }
  ]
}

=== AlanFSlaterCompanyNet/ShrForms/designs/design0/design0_1_2.json
{
  "$schema": "https://raw.githubusercontent.com/AlanFSlaterCompanyNet/PerFormOpen/master/PerFormOpen/schemas/formDesignSchema.json",
  "title": "A Form",
  "formTitle": "A Demo Form",
  "outputTable": "MyFirstOutputs",
  "readRole": "reader",
  "editRole": "editor",
  "pages": [
    {
      "name": "section1",
      "title": "Section One",
      "sectionLevel": 1,
      "fields": []
    },
    {
      "name": "page1",
      "title": "Page One",
      "fields": [
        {
          "name": "t1000",
          "type": "text",
          "label": "A text field for the demo",
          "tooltip": "This is a tooltip that can contain explanatory text for the field",
          "validation": "$value != 'banana'",
          "validationMessage": "Please don't say that",
          "help": "We can add some help text here"
        },
        {
          "name": "bool0",
          "label": "First",
          "type": "boolean",
          "help": "This is a boolean"
        },
        {
          "name": "bool1",
          "label": "Second",
          "type": "boolean",
          "help": "This is also a boolean, but the labels for the true and false values have been changed",
          "labelTrue": "Positive",
          "labelFalse": "Negative"
        },
        {
          "name": "percentage1",
          "label": "Percentage",
          "type": "numeric",
          "percentage": true
        },
        {
          "name": "n",
          "label": "Numeric > 10",
          "type": "numeric",
          "minimumValue": 10
        },
        {
          "name": "n2",
          "label": "No decimal places",
          "type": "numeric",
          "decimalPlaces": 0
        },
        {
          "name": "calculation",
          "label": "Divided by",
          "type": "numeric",
          "calculation": "n / n2"
        },
        {
          "name": "lenders",
          "type": "choice",
          "label": "Lenders (from CSV)",
          "csv": {
            "file": "lenders.csv",
            "labelColumn": "Lender",
            "valueColumn": "Short code"
          },
          "help": "A choice field where the values are read from a CSV file"
        }
      ]
    },
    {
      "name": "page2",
      "title": "Page Two",
      "fieldSettings": {
        "decimalPlaces": 1
      },
      "fields": [
        {
          "name": "text0",
          "label": "Text",
          "type": "text",
          "help": "Help text"
        },
        {
          "name": "bool0",
          "label": "Boolean",
          "type": "boolean",
          "help": "This is a boolean"
        },
        {
          "name": "text20",
          "label": "No help",
          "type": "text"
        },
        {
          "name": "date0",
          "label": "Start Date",
          "type": "date",
          "help": "Help text"
        },
        {
          "name": "date1",
          "label": "End Date",
          "type": "date",
          "validation": "$value > date0",
          "validationMessage": "Must be after Start Date",
          "help": "Help text"
        },
        {
          "name": "date2",
          "label": "Future date",
          "type": "date",
          "validation": "$value > (new Date())",
          "validationMessage": "Must be in the future",
          "help": "Help text"
        },
        {
          "name": "date3",
          "label": "Required date",
          "type": "date",
          "required": true,
          "help": "Help text"
        },
        {
          "name": "numeric0",
          "label": "First field",
          "type": "numeric",
          "minimumValue": 10,
          "help": "Help text"
        },
        {
          "name": "numeric1",
          "label": "Divide by this",
          "type": "numeric",
          "help": "Help text"
        },
        {
          "name": "total",
          "label": "Calculation with division",
          "type": "numeric",
          "calculation": "numeric0/numeric1",
          "help": "Help text"
        },
        {
          "name": "static",
          "type": "static",
          "style": "heading",
          "title": "Comments",
          "text": "must be entered if Total > 100",
          "help": "Help text"
        },
        {
          "name": "comments",
          "label": "Comments",
          "type": "text",
          "activation": "total > 100",
          "activationMode": "disable",
          "help": "Help text"
        },
        {
          "name": "choice",
          "label": "choice",
          "type": "choice",
          "values": [
            [ "value1", "Label 1" ],
            [ "value2", "Label 2" ]
          ],
          "help": "Help text"
        }
      ]
    },
    {
      "name": "section2",
      "title": "Section Two",
      "sectionLevel": 1,
      "fields": []
    },
    {
      "name": "page3",
      "title": "Second page",
      "fields": [
        {
          "name": "second",
          "type": "text",
          "label": "Field on page 2",
          "help": "Help text"
        }
      ]
    },
    {
      "name": "submit",
      "title": "Submit Page",
      "fields": [
        {
          "name": "submit",
          "type": "submit",
          "message": "Are you sure you want to submit this test form?",
          "width": 5
        }
      ]
    }
  ]
}
